# NextGIS OSMInfo Plugin
# Copyright (C) 2026  NextGIS
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or any
# later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, see <https://www.gnu.org/licenses/>.

import re
from typing import List, Optional, Union

from qgis.core import QgsApplication

from osminfo.core.constants import PLUGIN_NAME
from osminfo.core.exceptions import OsmInfoWizardRenderError

from .models import (
    ConditionNode,
    ConditionQueryType,
    MetaQueryType,
    RegexValue,
    RenderedWizardQuery,
    ResolvedConjunction,
    ResolvedWizardSearch,
    WizardBounds,
)


class OverpassWizardRenderer:
    """Render a resolved wizard search into Overpass QL.

    Convert resolved conjunctions, bounds, and metadata filters into executable
    Overpass clauses with a descriptive comment block.
    """

    _RELATIVE_DATE_PATTERN = re.compile(
        r"^-?\d+ ?(seconds?|minutes?|hours?|days?|weeks?|months?|years?)?$"
    )
    _REGEXP_ESCAPE_PATTERN = re.compile(r"([()\[{*+.$^\\|?])")

    def render(
        self,
        wizard_search: ResolvedWizardSearch,
        original_search: str,
        comment: Optional[str] = None,
    ) -> RenderedWizardQuery:
        query_parts: List[str] = []
        self._append_comment_block(query_parts, original_search, comment)
        query_parts.append("[out:json];")

        bounds_part = self._build_bounds_part(query_parts, wizard_search)
        rendered_clauses: List[str] = []

        for conjunction in wizard_search.conjunctions:
            clause_buffers = self._render_conjunction(
                conjunction,
                bounds_part,
            )
            rendered_clauses.extend(clause_buffers)

        if len(rendered_clauses) == 0:
            query_parts.append("(")
            query_parts.append(");")
        elif len(rendered_clauses) == 1:
            query_parts.append(rendered_clauses[0].lstrip())
        else:
            query_parts.append("(")
            query_parts.extend(rendered_clauses)
            query_parts.append(");")

        query_parts.append("out geom;")

        return RenderedWizardQuery(
            query="\n".join(query_parts),
            bounds=wizard_search.bounds,
            query_count=len(rendered_clauses),
            used_free_form=wizard_search.used_free_form,
        )

    def _append_comment_block(
        self,
        query_parts: List[str],
        original_search: str,
        comment: Optional[str],
    ) -> None:
        query_parts.append("/*")
        if comment is not None:
            query_parts.append(self._quote_comment_string(comment))
        else:
            query_parts.append(
                f"This query has been generated by the {PLUGIN_NAME} wizard."
            )
            query_parts.append("The original search was:")
            quoted_search = self._quote_comment_string(original_search)
            query_parts.append(f"“{quoted_search}”")
        query_parts.append("*/")

    def _build_bounds_part(
        self,
        query_parts: List[str],
        wizard_search: ResolvedWizardSearch,
    ) -> Optional[str]:
        if wizard_search.bounds == WizardBounds.AREA:
            if wizard_search.area is None:
                raise OsmInfoWizardRenderError(
                    log_message="Area bounds require area name",
                    user_message=self.tr("Area bounds require an area name."),
                )
            area = wizard_search.area
            query_parts.append(f"{{{{geocodeArea:{area}}}}}->.searchArea;")
            return "(area.searchArea)"

        if wizard_search.bounds == WizardBounds.AROUND:
            if wizard_search.area is None:
                raise OsmInfoWizardRenderError(
                    log_message="Around bounds require area name",
                    user_message=self.tr(
                        "Around bounds require an area name."
                    ),
                )
            area = wizard_search.area
            query_parts.append("{{radius=1000}}")
            return f"(around:{{{{radius}}}},{{{{geocodeCoords:{area}}}}})"

        if wizard_search.bounds == WizardBounds.BBOX:
            return "({{bbox}})"

        if wizard_search.bounds == WizardBounds.GLOBAL:
            return None

        raise OsmInfoWizardRenderError(
            log_message="Unknown wizard bounds",
            user_message=self.tr("Unknown wizard bounds."),
        )

    def _render_conjunction(
        self,
        conjunction: ResolvedConjunction,
        bounds_part: Optional[str],
    ) -> List[str]:
        clauses = [
            self._render_condition_clause(condition)
            for condition in conjunction.conditions
        ]

        if len(conjunction.types) == 0:
            return []

        type_names: List[str]
        if not conjunction.closed_way_only and len(conjunction.types) == 3:
            type_names = ["nwr"]
        else:
            type_names = [
                element_type.value for element_type in conjunction.types
            ]

        buffers: List[str] = []
        for type_name in type_names:
            buffer = f"  {type_name}"
            for clause in clauses:
                buffer += clause
            if conjunction.closed_way_only:
                buffer += "(if:is_closed())"
            if bounds_part is not None:
                buffer += bounds_part
            buffer += ";"
            buffers.append(buffer)

        return buffers

    def _render_condition_clause(self, condition: ConditionNode) -> str:
        query_type = condition.query
        key = condition.key if condition.key is not None else ""
        string_value = self._string_value(condition.val)
        regex_value = self._regex_value(condition.val)

        if query_type == ConditionQueryType.SUBSTR:
            query_type = ConditionQueryType.LIKE
            string_value = string_value or ""
            regex_value = RegexValue(
                regex=self._escape_regexp(string_value),
            )

        if string_value == "":
            if query_type == ConditionQueryType.EQ:
                query_type = ConditionQueryType.LIKE
                regex_value = RegexValue(regex="^$")
            elif query_type == ConditionQueryType.NEQ:
                query_type = ConditionQueryType.NOT_LIKE
                regex_value = RegexValue(regex="^$")

        if key == "":
            if query_type == ConditionQueryType.KEY:
                query_type = ConditionQueryType.LIKE_LIKE
                key = "^$"
                regex_value = RegexValue(regex=".*")
            elif query_type == ConditionQueryType.EQ:
                query_type = ConditionQueryType.LIKE_LIKE
                key = "^$"
                escaped_value = self._escape_regexp(string_value or "")
                regex_value = RegexValue(regex=f"^{escaped_value}$")
            elif query_type == ConditionQueryType.LIKE:
                query_type = ConditionQueryType.LIKE_LIKE
                key = "^$"

        if (
            query_type
            in (
                ConditionQueryType.LIKE,
                ConditionQueryType.LIKE_LIKE,
                ConditionQueryType.NOT_LIKE,
            )
            and regex_value is None
            and string_value is not None
        ):
            regex_value = RegexValue(regex=string_value)

        escaped_key = self._escape_overpass_value(key)
        escaped_value = self._escape_overpass_value(string_value)
        escaped_regex = self._escape_overpass_value(
            regex_value.regex if regex_value is not None else None
        )
        modifier = ""
        if regex_value is not None and len(regex_value.modifier) > 0:
            modifier = f",{regex_value.modifier}"

        if query_type == ConditionQueryType.KEY:
            return f'["{escaped_key}"]'
        if query_type == ConditionQueryType.NO_KEY:
            return f'["{escaped_key}"!~".*"]'
        if query_type == ConditionQueryType.EQ:
            return f'["{escaped_key}"="{escaped_value}"]'
        if query_type == ConditionQueryType.NEQ:
            return f'["{escaped_key}"!="{escaped_value}"]'
        if query_type == ConditionQueryType.LIKE:
            return f'["{escaped_key}"~"{escaped_regex}"{modifier}]'
        if query_type == ConditionQueryType.LIKE_LIKE:
            return f'[~"{escaped_key}"~"{escaped_regex}"{modifier}]'
        if query_type == ConditionQueryType.NOT_LIKE:
            return f'["{escaped_key}"!~"{escaped_regex}"{modifier}]'

        if query_type == ConditionQueryType.META:
            return self._render_meta_clause(condition, escaped_value)

        raise OsmInfoWizardRenderError(
            log_message=(
                f"Unknown wizard query type: {condition.query.value}"
            ),
            user_message=self.tr(
                "Unknown wizard query type: {query_type}."
            ).format(query_type=condition.query.value),
        )

    def _render_meta_clause(
        self,
        condition: ConditionNode,
        escaped_value: Optional[str],
    ) -> str:
        if condition.meta == MetaQueryType.ID:
            return f"({escaped_value})"
        if condition.meta == MetaQueryType.NEWER:
            raw_value = self._string_value(condition.val) or ""
            if self._RELATIVE_DATE_PATTERN.fullmatch(raw_value):
                return f'(newer:"{{{{date:{raw_value}}}}}")'
            return f'(newer:"{escaped_value}")'
        if condition.meta == MetaQueryType.USER:
            return f'(user:"{escaped_value}")'
        if condition.meta == MetaQueryType.UID:
            return f"(uid:{escaped_value})"

        raise OsmInfoWizardRenderError(
            log_message="Unknown wizard meta query",
            user_message=self.tr("Unknown wizard meta query."),
        )

    def _quote_comment_string(self, value: str) -> str:
        return value.replace("*/", "[…]").replace("\n", "\\n")

    def _string_value(
        self,
        value: Optional[Union[str, RegexValue]],
    ) -> Optional[str]:
        if isinstance(value, str):
            return value
        return None

    def _regex_value(
        self,
        value: Optional[Union[str, RegexValue]],
    ) -> Optional[RegexValue]:
        if isinstance(value, RegexValue):
            return value
        return None

    def _escape_overpass_value(self, value: Optional[str]) -> Optional[str]:
        if value is None:
            return None
        return (
            value.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\t", "\\t")
            .replace("\n", "\\n")
        )

    def _escape_regexp(self, value: str) -> str:
        return self._REGEXP_ESCAPE_PATTERN.sub(r"\\\1", value)

    @classmethod
    def tr(cls, message: str) -> str:
        return QgsApplication.translate(cls.__name__, message)
